// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAC-LFgIt2THZOrNK2ELBPNYCV57gFYBA',
    appId: '1:1083756400254:web:aabbed91030ed76f55d22f',
    messagingSenderId: '1083756400254',
    projectId: 'test-cf49f',
    authDomain: 'test-cf49f.firebaseapp.com',
    storageBucket: 'test-cf49f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwJq-nW2ztIB6WarLVWtADU0zdGfYFznE',
    appId: '1:1083756400254:android:cf6b06cf5d4c288655d22f',
    messagingSenderId: '1083756400254',
    projectId: 'test-cf49f',
    storageBucket: 'test-cf49f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjgXoLlgdkxRVeQIlCael0n_q-rgZ91tY',
    appId: '1:1083756400254:ios:4231e0a51c01bbff55d22f',
    messagingSenderId: '1083756400254',
    projectId: 'test-cf49f',
    storageBucket: 'test-cf49f.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjgXoLlgdkxRVeQIlCael0n_q-rgZ91tY',
    appId: '1:1083756400254:ios:4231e0a51c01bbff55d22f',
    messagingSenderId: '1083756400254',
    projectId: 'test-cf49f',
    storageBucket: 'test-cf49f.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAC-LFgIt2THZOrNK2ELBPNYCV57gFYBA',
    appId: '1:1083756400254:web:a12eba0d11cf20c655d22f',
    messagingSenderId: '1083756400254',
    projectId: 'test-cf49f',
    authDomain: 'test-cf49f.firebaseapp.com',
    storageBucket: 'test-cf49f.appspot.com',
  );

}